apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui-secrets
  namespace: open-webui
spec:
  encryptedData:
    OPENAI_API_KEY: AgAyolr1+RKHNIFfqtXod/ivrQubjlOYr0sn+uOMapryded/OD7+eZrLwHFc6RWLbrKZXHaAein+YO3LrFv9CR8EIFXD4F+HVJPXTMnHfpOR4urY7P34brgUjeyyFSBugbEQOJF+CvC+tpawil2x10tUdUK0Vz3AmG8YhSh6KEwU4J7RDkB6WN4obYLWKOgPoGwjd4GSKBudZnxBSBFNVH2T7BpO6EQUTIayNWWZ/j9uaiWtzM99nJJL7HOoQUXund93C+3CmixyihbdEzBXhUoY6dYBPXf1uved98P+YC1w7oD5qY7l/RDxuSECrM4XszwA6IZOgIcSi22bcxuxdjyeo4NNCDa2C0LAfw+c4NrKqZ/+nw0KseR0vjDKzpRACNu9gDvum40QVM0A0zwdI8JVusfCRJTGBs+BkyIhUtHzkxc5fVOmBlTipFMCSmicendvHE30RF88Lxdr1sJKoKLN+dzTm2RtribAwlPb2Qb3S3TiiDhN4V2QOLGa1cKtDz/lGs+me1agde2Eyl+fxCbbXSopd9QPp1/OoHzOr/xT+PLpHMe2ZY7LZsHWRRb1DVY0aHdOBDpnsaFQ9f/OC46tWdRUBEs5OM7jaqKK3eojlfLo/ztMUO3nDdESjedUnFFGTjLT3zVBxMWer6THkHgRWbqF3J52ckHj7votRnnczVJHiK+gbaB/9AmNlg6JWiSiQuC5rzB/E3H3+qqm1+ljo/9+2jKTDTmR2cqARx5EmqmS/scn0Swo+Hxt3IXlVzaIVH1paEAxjcEfVyyeqXO+9LZ2XuH0pVTH
  template:
    metadata:
      name: open-webui-secrets
      namespace: open-webui
