apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busybox
  namespace: argocd
spec:
  destination:
    namespace: busybox
    server: https://kubernetes.default.svc
  project: default
  source:
    path: busybox
    repoURL: https://github.com/ARGI-BERRI/manifests.git
    targetRevision: main
  syncPolicy:
    automated: {}
