apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  project: default
  sources:
    - chart: open-webui
      repoURL: https://helm.openwebui.com/
      targetRevision: 12.0.1
      helm:
        releaseName: open-webui
        valuesObject:
          ollama:
            enabled: false
          pipelines:
            enabled: false
          openaiBaseApiUrl: "https://openrouter.ai/api/v1"
          extraEnvVars:
            - name: ENABLE_IMAGE_GENERATION
              value: "True"
            - name: CHAT_STREAM_RESPONSE_CHUNK_MAX_BUFFER_SIZE
              value: "20971520"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: open-webui-secrets
                  key: OPENAI_API_KEY
    - path: open-webui
      repoURL: https://github.com/ARGI-BERRI/manifests.git
      targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: open-webui
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
