apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
spec:
  destination:
    namespace: open-webui
    server: https://kubernetes.default.svc
  project: default
  source:
    path: open-webui
    repoURL: https://github.com/ARGI-BERRI/manifests.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
