apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-secrets
  namespace: default
spec:
  encryptedData:
    TUNNEL_TOKEN: AgCABDX/fdPwkDWy0POWQum9STrdQylCqincHr/k6v0cf/Ali7+plhwvTc+/AoBpNO5lpi94xWEFFLAwlySNPniRwiyyn8LYCwWhudkwLC95a63mHO9BN1bPEWAj2Kgx/Ia/fhAeMfD6KPNChyMRMi2DZqD9N560NSPTh/ReVquydZI99iDBuVkhUMXG8URxwU3FwwgjkBXX7xso03BHJ7zF1YDupSiaer0uefRzEm6NRC9zwDtHLwsHCtvj6FzpfqwEaBXyt2JVtz2xwKol9hhFKyVWL1kYXk43wnH835C1PLYgoZ+5b2b6NOJaOwg+4ZF21ckFm1m+eS8gM935REtQ0P6ie0CDYzFyvRSj1tI4XIQCk8w6mKeS/cK7n8aMT8RJmGbZ14ZzFX2F2G10UyhJ3yTXzQHWPsPqzqQWbTN6keXp5lxiTkZbXttJvDaCp4iUJ2oY6qoQIsBOFmgeaO+WAX6tbtBUnbpRjhcMzmkra+DgPexeGvq+h3MTDgBUCM3iQsb5uMmFkVWzKVzS3N+2NKCgz3ofwEtofhvQXUKDe0/qwMVgR4iBckVwX8As1tj1hPB/JVNyFjsFS3X4odhinGFBHMHjYZmV0b7OkDR4fw401o4p6IEt0SMNoKFkFoaz5eR/0A4uttctUbZ1hVmhhG2feBjuSu+OCi0H8whYl0L7dqFrezXipf+wNS0FA60cIeBvbmE+HMxMMVyDq+QlBRpCQPxXjh5/pXCrOmEWExISvTeATNZjpQZa1fq/I1WXzlUeScE2HOvKIYyWEu/FWWtKHyVJ/deA0jB9AHF+/9feZDLO3NVi5Au5QUc0FFJeTw4+vJV0fdtzLCpVRaczauNvaVhTW3Hg8fRWb+5AYuxHCpNxp9sCJxI7eFKetm2lMYmk6CqqvABjRj9e/KEoiqd19dNFN0LbbI9UIfMGs5vbCy5JicQl7Q==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-secrets
      namespace: default
