apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox
          command:
            - sleep
            - "3600"
          resources:
            limits:
              memory: 128Mi
              cpu: "0.1"
          env:
            - name: BUSYBOX_SECRET
              valueFrom:
                secretKeyRef:
                  name: sample-secret
                  key: BUSYBOX_SECRET
